/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/create-job`; params?: Router.UnknownInputParams; } | { pathname: `/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/subscription`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/jobs` | `/jobs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/messages` | `/messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-jobs` | `/my-jobs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/people` | `/people`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/job/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/job-applicants/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/person/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/review/[jobId]`, params: Router.UnknownInputParams & { jobId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/create-job`; params?: Router.UnknownOutputParams; } | { pathname: `/edit-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `/subscription`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/jobs` | `/jobs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/messages` | `/messages`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my-jobs` | `/my-jobs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/people` | `/people`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/chat/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/job/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/job-applicants/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/person/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/review/[jobId]`, params: Router.UnknownOutputParams & { jobId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/create-job${`?${string}` | `#${string}` | ''}` | `/edit-profile${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `/subscription${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/jobs${`?${string}` | `#${string}` | ''}` | `/jobs${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/messages${`?${string}` | `#${string}` | ''}` | `/messages${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my-jobs${`?${string}` | `#${string}` | ''}` | `/my-jobs${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/people${`?${string}` | `#${string}` | ''}` | `/people${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/create-job`; params?: Router.UnknownInputParams; } | { pathname: `/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/subscription`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/jobs` | `/jobs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/messages` | `/messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-jobs` | `/my-jobs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/people` | `/people`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/job/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/job-applicants/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/person/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/review/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/job/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/job-applicants/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/person/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/review/[jobId]`, params: Router.UnknownInputParams & { jobId: string | number; } };
    }
  }
}
